# Homework 4 Mardown

<!--OL--># Homework 4 

<!--OL-->

1. What does one need to do to use a module?

<font color= green>
One must group related code into a file with the extention ".py" to use a module. </font>

2. Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code 

<font color= green>
Random Module
import random
prob = random.random()
print("Probability ...", prob)
 </font>


3. as an example using this module.
<font color= green>
Probability ... 0.03217154321123428 </font>

1. What is a benefit of using Exception handling? 
<font color= green>
The benefits of using Exception handling is that it normally stop and generate an error message when something goes wrong.</font> 
    

1. What are the 4 components used for Python Exception Handling?
<font color= green>
The 4 components for Python exception handling is as follow:</font>  
 * try block lets you test a block of code for errors. 
    *  block lets you handle the error.
    * The else block lets you execute code when there is no error.
    * The finally block lets you execute code, regardless of the result of the try- and except blocks.


5. NumPy arrays are like what Python data types?
    * integer
    * string
    * range
    * float


1. What is one of the main benefits of using NumPy arrays.
<font color= green>
It contains a multidimensional array and matrix data structure (in the form of rows and columns) </font>


1. What is one of the main requirements about the 'dtype' of NumPy arrays?
<font color= green>
specify which data type you want </font>

1. Of the 10 uses of NumPy, name 
    * Broadcasting
    * Mathematical Operations


1. Name one of the other libraries we'll use with NumPy?
    * Pandas


1. What is the shape of NumPy arrays?
<font color= green>
As the number of elements in each dimension are the same, use numpy.reshape() </font>

1. What is a Tensor?
<font color= green>
mathematical objects that can be used to describe physical properties </font>


1. Name a reason why it's better using NumPy for Data Analysis than using a Python List?
    * Less Memory - NumPy arrays occupy less memory as compared to list
    * Fast - NumPy arrays are fast compared to lists
    * Convenient - it is convenient to work with NumPy


1. When creating an "empty" array, where do the elements come from?
<font color= green>
 The reason to use empty() over zeros() (or something similar) is speed - just make sure to fill every element afterwards!</font>



In [85]:
# using Date Time
import datetime as dt

# Get Current Date and Time
a = dt.datetime.now()
print("Current Date and Time ...", a)


# "strftime()" EXAMPLES
import datetime
example = datetime.datetime.now()
print("Month ...", example.strftime("%B"))


# Write a simple function that takes 2 parameters -- a first name and a day name.
name="Kayla"
message = ( 
    f"Name ... {name}."
)
print (message)
print("Day ... ", example.strftime("%A"))


# Set a default value for the day name of Sunday.
x = "Sunday"
print(x)

#Have the function print out a greeting -- using the parameters -- that says something like "Hi first-name! Happy day-name!".
message = ( 
    f"Hi {name}! Happy {x}!"
)
print (message)

#Write a block of code to handle one of the most common Python exception errors. 
# This will cause an error as x is not defined
try:
    print(g)
except:
    print("An exception occurred")

try:
    print(g)
except NameError:
    print("Variable x is not defined")
except:
    print("Something else went wrong")

try: 
    print("Goodbye")
except:
    print("Something went wrong")
else:
    print("Nothing went wrong")

try:
    print(g)
except:
    print("Something went wrong")
finally:
    print("The 'try except' is finished")


#create an array with a shape of ... (2, 3, 2)
a_2d = np.arange(12).reshape((2, 3, 2))
print("The a_2d array ...\n", a_2d)

# create an array with linearly spaced values at a specified interval
import numpy as np

# create an array with linearly spaced values at a specified number of intervals
# range from 0 up to 20 in 6 intervals -- including 0 and 20
g = np.linspace(0, 20, num=6)
print("Array g ...", g)


# best way to DEEP copy a NumPy Array:
import copy

xArray = [(2,3,2)]
zArray = copy.deepcopy(xArray)

print("The xArray ...\n", xArray)
print("\nThe zArray ...\n", xArray)


#Using NumPy, 'broadcast' the multiplication of the following 2 arrays below to a 2-D array using the newaxis parameter ...


Current Date and Time ... 2023-02-20 10:02:01.386373
Month ... February
Name ... Kayla.
Day ...  Monday
Sunday
Hi Kayla! Happy Sunday!
[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]
Goodbye
Nothing went wrong
[ 0.  4.  8. 12. 16. 20.]
The 'try except' is finished
The a_2d array ...
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Array g ... [ 0.  4.  8. 12. 16. 20.]
The xArray ...
 [(2, 3, 2)]

The zArray ...
 [(2, 3, 2)]


In [87]:
# transforming arrays for Broadcasting with`newaxis`
from numpy import array, newaxis

aa = array([0.71, 0.1, 0.24, 0.3])
bb = array([0.8, 0.59, 1.0, 1.11])

print("The sum of aa and bb ...\n")
print(aa[:,newaxis] + bb)

The sum of aa and bb ...

[[1.51 1.3  1.71 1.82]
 [0.9  0.69 1.1  1.21]
 [1.04 0.83 1.24 1.35]
 [1.1  0.89 1.3  1.41]]
