<!-- Headings -->
Homework 5 


<! --OL-->

1. What does Pandas stand for? 

<font color= green> An open-source Python package that is most widely used for data science/data analysis and machine learning tasks. </font>

2. What are the 2 collections used in Pandas?

<font color= green> “Panel Data” and “Python Data Analysis”</font>

3. Name 4 things Pandas can do for us. 

<font color= green>

   * Data Cleansing
   * Data normalization
   * Data visualization
   * Data inspection
 </font>



4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

<font color= green>
_values
</font>

5. What is a CSV?

<font color= green>
CSV files contains plain text and is a well know format that can be read by everyone including Pandas.
</font>


6. When cleaning data what values do we not like in our data?

    * Values like 0
    * NA
    * None
    * Null
    * INF

In [24]:
#Concatenate these 3 arrays into a new array named 'newArray'
# ([[25, 16]])
#([[11, 2], [13, 4]])
#([[7, 81], [5, 6], [11, 12]])

# reshaping a NumPy 
import numpy as np

aArray = np.array([[25, 16]])
bArray = np.array([[11, 2], [13, 4]])
cArray = np.array([[7, 81], [5, 6], [11, 12]])


print("aArray original shape ...\n", aArray)

newShape1 = np.reshape(aArray, 2)
print("newShape1 ...", newShape1)

newShape2 = bArray.reshape(2,2)
print("\n reshaping bArray ...\n", newShape2)

newShape3 = cArray.reshape(2,3)
print("\n reshaping cArray ...\n", newShape3)

aArray original shape ...
 [[25 16]]
newShape1 ... [25 16]

 reshaping bArray ...
 [[11  2]
 [13  4]]

 reshaping cArray ...
 [[ 7 81  5]
 [ 6 11 12]]
